services:
    Sidus\ElasticaFilterBundle\Filter\Type\AutocompleteDataFilterType:
        public: false
        arguments:
            - autocomplete_data
            - Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
        tags:
            - { name: sidus.filter_type }

    Sidus\ElasticaFilterBundle\Filter\Type\DateRangeFilterType:
        public: false
        arguments:
            - date_range
            - Sidus\FilterBundle\Form\Type\DateRangeType
        tags:
            - { name: sidus.filter_type }

    # Simple alias for text filter type for backward compatibility
    sidus.elastica_filter.filter.type.text:
        class: Sidus\ElasticaFilterBundle\Filter\Type\MatchFilterType
        public: false
        arguments:
            - text
            - Symfony\Component\Form\Extension\Core\Type\TextType
        tags:
            - { name: sidus.filter_type }

    Sidus\ElasticaFilterBundle\Filter\Type\MatchFilterType:
        public: false
        arguments:
            - match
            - Symfony\Component\Form\Extension\Core\Type\TextType
        tags:
            - { name: sidus.filter_type }

    Sidus\ElasticaFilterBundle\Filter\Type\WildcardFilterType:
        public: false
        arguments:
            - wildcard
            - Symfony\Component\Form\Extension\Core\Type\TextType
        tags:
            - { name: sidus.filter_type }

    Sidus\ElasticaFilterBundle\Filter\Type\ChoiceFilterType:
        public: false
        arguments:
            - choice
            - Symfony\Component\Form\Extension\Core\Type\ChoiceType
        tags:
            - { name: sidus.filter_type }
