services:
    sidus.elastica.registry.finder:
        class: Sidus\ElasticaFilterBundle\Registry\ElasticaFinderRegistry

    sidus.elastica.registry.searchable:
        class: Sidus\ElasticaFilterBundle\Registry\ElasticaSearchableRegistry
